// Functional component to display AI response and user prompt
const AiResponseDisplay = ({
  userPrompt, // The prompt or query provided by the user
  aiResponse, // The response generated by the AI based on the user's prompt
}: {
  userPrompt: string; // Type definition for userPrompt as a string
  aiResponse: string; // Type definition for aiResponse as a string
}) => {
  return (
    <div className="mt-4"> {/* Wrapper div with margin-top for spacing */}
      <div className="w-full flex justify-end"> {/* Flex container for right-alignment */}
        {/* Displaying the user's prompt */}
        <div className="max-w-[75%] p-2 mb-6 bg-[#dfe1e7] rounded-xl text-[#666d80] text-2xl leading-9">
          {userPrompt} {/* Render the user prompt inside the styled div */}
        </div>
      </div>
      {/* Displaying the AI's response */}
      <div className="max-w-[75%] p-2 bg-blue-100 rounded-xl text-[#666d80] text-2xl leading-9 mb-6">
        {aiResponse} {/* Render the AI response inside the styled div */}
      </div>
    </div>
  );
};

// Exporting the AiResponseDisplay component for use in other modules
export default AiResponseDisplay;
